### ISSUE TITLE
Made a plugin for Vite

### ISSUE THREAD

**Issue by antfu** [voorjaar/windicss#14]
In case you haven't heard about it, [Vite](https://github.com/vitejs/vite) is a dev server and a bundler built on top of ESM with the idea of on-demand transpiling. It's blazing fast.

I am a heavy user of Tailwind with Vite, but Tailwind has a huge overhead in terms of HMR. Found this project today, and it looks quite promising and fits perfectly with Vite's notion. So I gave it a try and made a Vite plugin for windicss (just an MVP atm):

https://github.com/antfu/vite-plugin-windicss

Posting here for someone looking for a similar thing. Also would love to hear what you think about it. Feel free to close.

Thanks for the awesome work on this project and really looking forward to seeing where it will go.

PS. more context about this on Vite's discord server:
https://discord.com/channels/804011606160703521/804082351624945695/810136889969475594

**Comment by voorjaar** [comment]
Well done. But it seems that you are using vue. I don't know if vite can load vue-loader. I think it might be better to use [vue-loader](https://github.com/voorjaar/vue-windicss-preprocess) so that you can use features such as tailwind directive or code splitting.

**Comment by antfu** [comment]
Vite is based on Rollup so unfortunately it can't use `vue-loader`. Eventually, I will make the directive and code splitting works (and will also support React, Svelte, etc) 😉.

**Comment by voorjaar** [comment]
Added to the [homepage](https://github.com/voorjaar/windicss) and [wiki](https://github.com/voorjaar/windicss/wiki/Getting-started#using-with-preprocessors), and then I will close this issue.
