### ISSUE TITLE
Config resolve not correct when extend width or height.

### ISSUE THREAD

**Issue by hannoeru** [voorjaar/windicss#18]
In resolveConfig if theme property is function, extendTheme will overwrite it. then you will lost default config in that part.

**Comment by antfu** [comment]
Can you share some examples of your config?

**Comment by hannoeru** [comment]
```json5
{
  theme: {
    extend: {
      opacity: {
        15: '0.15',
        20: '0.2',
        95: '0.95',
      },
      margin: {
        96: '24rem',
        128: '32rem',
      },
      padding: {
        '2/3': '66.666%',
      },
      height: {
        18: '4.5rem',
      },
      width: {
        18: '4.5rem',
      },
    },
  },
  variants: {
    extend: {
      translate: ['group-hover'],
      animation: ['group-hover'],
      backgroundOpacity: [
        'dark',
        'active',
      ],
    },
  },
  darkMode: 'class',
}
```

**Comment by hannoeru** [comment]
because `this._resolveConfig` add `extendTheme` to `theme` in
https://github.com/voorjaar/windicss/blob/174dc7f960852bac68a0e34d797e6a4d5c2b4dd5/src/lib/index.ts#L115-L117 before all functions got resolved in 
https://github.com/voorjaar/windicss/blob/174dc7f960852bac68a0e34d797e6a4d5c2b4dd5/src/lib/index.ts#L169
some of the default theme property are functions, so it got replaced by extend theme.

**Comment by hannoeru** [comment]
@voorjaar  Thanks !!
