### ISSUE TITLE
Support of tailwind directives

### ISSUE THREAD

**Issue by juanvillacortac** [voorjaar/windicss#4]
Hello, are planned the implementations of Tailwind directives? Like:
```css
.btn {
  @apply p-2;
  @apply bg-green-500;
  @apply duration-200;
  @apply text-lg;
}

.btn:hover {
  @apply bg-green-400;
}

/* Or... */

@screen lg {
  .btn {
    @apply text-xl;
  }
}
```

This project is amazing!

**Comment by voorjaar** [comment]
Yes, I'm going to implement it, but I'm going to start the implementation after modifying the programming interface, because we gonna need a new css parser, which is not easy to implement.

**Comment by voorjaar** [comment]
[v1.2.0](https://github.com/voorjaar/windicss/commit/34ae628033d112b6c7dd4ad84366dd4778e5e9ea) has been released.

This version added @apply and @screen support, and they should be available after I update svelte-windicss-preprocess.
